### ISSUE TITLE
Does not support inline function definitions?

### ISSUE THREAD

**Issue by btrevizan** [Calysto/scilab_kernel#4]
Hello,

I was using scilab_kernel in Jupyter. I used the 'for ... end' statement, like:
```
for i=1:10
 disp(i)
end
```
And the kernel froze. I had to restart the Jupyter server. So, can't I use multi line statements?

**Comment by blink1073** [comment]
Looks like a bug.  It works if you use the single line form: `for i=1:1; disp(i); end`.

**Comment by blink1073** [comment]
This is fixed in v0.9.0 (`pip install scilab_kernel==0.9`).

**Comment by pedrohnv** [comment]
Can this be adressed? Because readability is affected by that, like when having to define a function as the following:

`function theta=departure_angle(pi, zer, pol); yp = 0; for i = 1:size(pol)(1); x = pi - pol(i); yp = yp + atan(imag(x), real(x)); end; yz = 0; for i = 1:size(zer)(1); x = pi - zer(i); yz = yz + atan(imag(x), real(x)); end; theta = 180 + (yz - yp)*180/%pi; endfunction;`

It seems that jupyter sends the commands line by line, only sending the next after receiving an output from the kernel. But Scilab's kernel only outputs after it receives an `end` statement. Hence it hangs... I've looked at task manager, and the scilab console has no activity when it freezes that way.

A workaround, for the sake of readability, is to put the formatted code surronded by quotes in a Markdown cell; then put the command in one line in a Code cell.

**Comment by blink1073** [comment]
I just tried this on macOS 10.13 with Scilab 6.0.0 and it worked as expected:

```octave
function theta=departure_angle(pi, zer, pol)
   yp = 0; 
   for i = 1:size(pol)(1); 
       x = pi - pol(i); 
       yp = yp + atan(imag(x), real(x)); 
    end; 
    yz = 0; 
    for i = 1:size(zer)(1); 
        x = pi - zer(i); 
        yz = yz + atan(imag(x), real(x)); 
    end; 
    theta = 180 + (yz - yp)*180/%pi; 
endfunction;
departure_angle(10, 10, 10)
```

Which platform and scilab version are you using?

**Comment by pedrohnv** [comment]
I am using Scilab 6.0.0, Windows 10. Both 64 bit.

In connection to my last comment in the [other issue](https://github.com/Calysto/scilab_kernel/issues/3), I've corrected my SCILAB_EXECUTABLE variable to point to `Scilex` instead of `WScilex`. I tried changing the `executable` in line 62 of `kernel.py` from `WScilex` back to `Scilex`. This issue still happens.

**Comment by blink1073** [comment]
Confirmed that it doesn't work work on Windows 10.  I'll have to do some digging to figure why.

**Comment by blink1073** [comment]
The problem is that on Windows we aren't getting the continuation prompts after each line.  On posix systems, we can use a `pty` and it behaves as if we were running in the terminal. 
What we need is a flag for a subprocess based kernel as to whether we should process line by line.  In this case we would set it to `False` on Windows for this kernel.

**Comment by blink1073** [comment]
This should be fixed now by upgrading `metakernel`: `pip install metakernel==0.20.11`.

**Comment by pedrohnv** [comment]
It works with metakernel upgraded.

**Comment by blink1073** [comment]
Great!

**Comment by hchesser** [comment]
I am having this issue on Windows 10, I actually downgraded to metakernel 0.20.11 (installed 0.20.14 originally).  I tried changing my SCILAB_EXECUTABLE from WScilex.exe to Scilex.exe.

I am running Windows 10, Scilab-5.5.2, Jupyter Notebook (Ananconda3).  

When I try running anything in the first cell in a Jupyter Notebook with the Scilab kernel, it just hangs.  No error messages or anything in the console window...
